# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae3a6a2b07175fee3aaf631d479ef79e101f5658458acaeacfb301dbf9ad6c63d2bb3f24138174db8127f35c9b71870afbdcd1936065cd1f946f64898254f44a

test:
  secret_key_base: b97bb5df06e8f6718251e0dc779dcc05385b004c325a8de6fed789e2cc63ac32f95e4ffb02ec41f59ad9e206c6ff0a7ea70fd3a4775f475ea9ece4c2c7dde148

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
